# Generated by Django 6.0.1 on 2026-03-19 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecorridoProximo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo')),
                ('imagen', models.ImageField(upload_to='recorridos/', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recorrido Próximo',
                'verbose_name_plural': 'Próximos Recorridos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RecorridoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo')),
                ('imagen', models.ImageField(upload_to='recorridos/', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recorrido Realizado',
                'verbose_name_plural': 'Recorridos Realizados',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PreInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('recorrido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.recorridoproximo', verbose_name='Recorrido')),
            ],
            options={
                'verbose_name': 'Preinscripción',
                'verbose_name_plural': 'Preinscripciones',
                'ordering': ['-created'],
            },
        ),
    ]
