# Generated by Django 6.0.1 on 2026-03-26 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_recorridoproximo_descripcion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecorridoProximo',
            new_name='Recorrido',
        ),
        migrations.DeleteModel(
            name='RecorridoRealizado',
        ),
        migrations.AlterModelOptions(
            name='recorrido',
            options={'ordering': ['fecha'], 'verbose_name': 'Recorrido', 'verbose_name_plural': 'Recorridos'},
        ),
    ]
