# Generated by Django 6.0.1 on 2026-04-22 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_preinscripcion_usuario_opinion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinion',
            name='recorrido',
        ),
    ]
